# Generated by Django 5.1.2 on 2024-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_available_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_content_available',
            field=models.BooleanField(default=True, verbose_name='Содержание доступно'),
        ),
    ]
